#if 0
#elif defined(__arm64__) && __arm64__
// Generated by Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
#ifndef CLOVERCONNECTOR_SWIFT_H
#define CLOVERCONNECTOR_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CloverConnector",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC15CloverConnector7Message")
@interface Message : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector22AcknowledgementMessage")
@interface AcknowledgementMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector25BaseActivityRemoteMessage")
@interface BaseActivityRemoteMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector27ActivityMessageFromActivity")
@interface ActivityMessageFromActivity : BaseActivityRemoteMessage
@end


SWIFT_CLASS("_TtC15CloverConnector25ActivityMessageToActivity")
@interface ActivityMessageToActivity : BaseActivityRemoteMessage
@end


SWIFT_CLASS("_TtC15CloverConnector15ActivityRequest")
@interface ActivityRequest : Message
@end


SWIFT_CLASS("_TtC15CloverConnector23ActivityResponseMessage")
@interface ActivityResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector22BaseTransactionRequest")
@interface BaseTransactionRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Provides base capabilities for TransactionRequests like SaleRequest, AuthRequest, etc.
SWIFT_CLASS("_TtC15CloverConnector18TransactionRequest")
@interface TransactionRequest : BaseTransactionRequest
@end


/// The request sent to the Auth method. ‘amount’ is the only field required.
SWIFT_CLASS("_TtC15CloverConnector11AuthRequest")
@interface AuthRequest : TransactionRequest
@end


/// A base response for
SWIFT_CLASS("_TtC15CloverConnector12BaseResponse")
@interface BaseResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector15PaymentResponse")
@interface PaymentResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The response to an auth request
SWIFT_CLASS("_TtC15CloverConnector12AuthResponse")
@interface AuthResponse : PaymentResponse
@end


/// Base message used for exchanging messages between the POS and a Custom Activity
SWIFT_CLASS("_TtC15CloverConnector19BaseActivityMessage")
@interface BaseActivityMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





SWIFT_CLASS("_TtC15CloverConnector12BreakMessage")
@interface BreakMessage : Message
@end


/// options for capturing a pre-auth
SWIFT_CLASS("_TtC15CloverConnector21CapturePreAuthRequest")
@interface CapturePreAuthRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector30CapturePreAuthRequestMessageV1")
@interface CapturePreAuthRequestMessageV1 : Message
@end


/// response to a capturePreAuth request
SWIFT_CLASS("_TtC15CloverConnector22CapturePreAuthResponse")
@interface CapturePreAuthResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector29CapturePreAuthResponseMessage")
@interface CapturePreAuthResponseMessage : Message
@end

@class NSCoder;

SWIFT_CLASS("_TtC15CloverConnector8CardData")
@interface CardData : NSObject <NSCoding>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector22CardDataRequestMessage")
@interface CardDataRequestMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector23CardDataResponseMessage")
@interface CardDataResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector23CashbackSelectedMessage")
@interface CashbackSelectedMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector15CloseoutRequest")
@interface CloseoutRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector22CloseoutRequestMessage")
@interface CloseoutRequestMessage : Message
@end


/// response to a closeout request
SWIFT_CLASS("_TtC15CloverConnector16CloseoutResponse")
@interface CloseoutResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector23CloseoutResponseMessage")
@interface CloseoutResponseMessage : Message
@end


/// generic message for unanticipated or unexpected errors
SWIFT_CLASS("_TtC15CloverConnector22CloverDeviceErrorEvent")
@interface CloverDeviceErrorEvent : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector17CloverDeviceEvent")
@interface CloverDeviceEvent : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// requests the device log a message to the server
SWIFT_CLASS("_TtC15CloverConnector22CloverDeviceLogMessage")
@interface CloverDeviceLogMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector15CloverTransport")
@interface CloverTransport : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector21ConfirmPaymentMessage")
@interface ConfirmPaymentMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector21ConfirmPaymentRequest")
@interface ConfirmPaymentRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector18CreditPrintMessage")
@interface CreditPrintMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector21CustomActivityRequest")
@interface CustomActivityRequest : BaseActivityMessage
@end


/// response when a custom activity is finished
SWIFT_CLASS("_TtC15CloverConnector22CustomActivityResponse")
@interface CustomActivityResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector19CustomerInfoMessage")
@interface CustomerInfoMessage : Message
@end


/// Loyalty API
/// Transfers the data provided by the customer to the semi-integrated POS
SWIFT_CLASS("_TtC15CloverConnector25CustomerProvidedDataEvent")
@interface CustomerProvidedDataEvent : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector27CustomerProvidedDataMessage")
@interface CustomerProvidedDataMessage : Message
@end



SWIFT_CLASS("_TtC15CloverConnector25DeclineCreditPrintMessage")
@interface DeclineCreditPrintMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector26DeclinePaymentPrintMessage")
@interface DeclinePaymentPrintMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector30DefaultCloverConnectorListener")
@interface DefaultCloverConnectorListener : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Contains information about the connected device
SWIFT_CLASS("_TtC15CloverConnector10DeviceInfo")
@interface DeviceInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector23DiscoveryRequestMessage")
@interface DiscoveryRequestMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24DiscoveryResponseMessage")
@interface DiscoveryResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector12DisplayOrder")
@interface DisplayOrder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector28DisplayReceiptOptionsRequest")
@interface DisplayReceiptOptionsRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector29DisplayReceiptOptionsResponse")
@interface DisplayReceiptOptionsResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector19FinishCancelMessage")
@interface FinishCancelMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector15FinishOkMessage")
@interface FinishOkMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector17ImagePrintMessage")
@interface ImagePrintMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector23IncrementPreauthMessage")
@interface IncrementPreauthMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24IncrementPreauthResponse")
@interface IncrementPreauthResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The response
SWIFT_CLASS("_TtC15CloverConnector31IncrementPreauthResponseMessage")
@interface IncrementPreauthResponseMessage : Message
@end

@class NSString;

SWIFT_CLASS("_TtC15CloverConnector11InputOption")
@interface InputOption : NSObject
@property (nonatomic, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector30InvalidStateTransitionResponse")
@interface InvalidStateTransitionResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector15KeyPressMessage")
@interface KeyPressMessage : Message
@end


/// options for a manual refund
SWIFT_CLASS("_TtC15CloverConnector19ManualRefundRequest")
@interface ManualRefundRequest : TransactionRequest
@end


/// response to a manual refund
SWIFT_CLASS("_TtC15CloverConnector20ManualRefundResponse")
@interface ManualRefundResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Contains merchant information as well as some high level capabilities
SWIFT_CLASS("_TtC15CloverConnector12MerchantInfo")
@interface MerchantInfo : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



/// Contains the message information send from a custom Activity
SWIFT_CLASS("_TtC15CloverConnector19MessageFromActivity")
@interface MessageFromActivity : BaseActivityMessage
@end


/// Contains the message information sent to a custom Activity
SWIFT_CLASS("_TtC15CloverConnector17MessageToActivity")
@interface MessageToActivity : BaseActivityMessage
@end


SWIFT_CLASS("_TtC15CloverConnector21OpenCashDrawerMessage")
@interface OpenCashDrawerMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector21OpenCashDrawerRequest")
@interface OpenCashDrawerRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector29OrderActionAddDiscountMessage")
@interface OrderActionAddDiscountMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector26OrderActionLineItemMessage")
@interface OrderActionLineItemMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector32OrderActionRemoveDiscountMessage")
@interface OrderActionRemoveDiscountMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector32OrderActionRemoveLineItemMessage")
@interface OrderActionRemoveLineItemMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector26OrderActionResponseMessage")
@interface OrderActionResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector18OrderUpdateMessage")
@interface OrderUpdateMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector18PartialAuthMessage")
@interface PartialAuthMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector23PaymentConfirmedMessage")
@interface PaymentConfirmedMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector31PaymentPrintMerchantCopyMessage")
@interface PaymentPrintMerchantCopyMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector19PaymentPrintMessage")
@interface PaymentPrintMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector22PaymentRejectedMessage")
@interface PaymentRejectedMessage : Message
@end



SWIFT_CLASS("_TtC15CloverConnector20PaymentVoidedMessage")
@interface PaymentVoidedMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector19PendingPaymentEntry")
@interface PendingPaymentEntry : NSObject <NSCoding>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// options for a pre-authorization request
SWIFT_CLASS("_TtC15CloverConnector14PreAuthRequest")
@interface PreAuthRequest : BaseTransactionRequest
@end


/// response to a pre-auth request
SWIFT_CLASS("_TtC15CloverConnector15PreAuthResponse")
@interface PreAuthResponse : PaymentResponse
@end


SWIFT_CLASS("_TtC15CloverConnector21PrintJobStatusRequest")
@interface PrintJobStatusRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector28PrintJobStatusRequestMessage")
@interface PrintJobStatusRequestMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector22PrintJobStatusResponse")
@interface PrintJobStatusResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector29PrintJobStatusResponseMessage")
@interface PrintJobStatusResponseMessage : Message
@end


/// Callback to the POS to request a manual refund declined receipt
SWIFT_CLASS("_TtC15CloverConnector38PrintManualRefundDeclineReceiptMessage")
@interface PrintManualRefundDeclineReceiptMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Callback to request the POS print a refund for a
/// ManualRefund
SWIFT_CLASS("_TtC15CloverConnector31PrintManualRefundReceiptMessage")
@interface PrintManualRefundReceiptMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Callback to the POS to request a payment declined receipt
SWIFT_CLASS("_TtC15CloverConnector33PrintPaymentDeclineReceiptMessage")
@interface PrintPaymentDeclineReceiptMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// <ul>
///   <li>
///     Callback to the POS to request a merchant copy of the payment receipt
///   </li>
/// </ul>
SWIFT_CLASS("_TtC15CloverConnector38PrintPaymentMerchantCopyReceiptMessage")
@interface PrintPaymentMerchantCopyReceiptMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Callback to the POS to request a payment receipt be printed
SWIFT_CLASS("_TtC15CloverConnector26PrintPaymentReceiptMessage")
@interface PrintPaymentReceiptMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// <ul>
///   <li>
///     Callback to the POS to request a refund payment receipt
///   </li>
/// </ul>
SWIFT_CLASS("_TtC15CloverConnector32PrintRefundPaymentReceiptMessage")
@interface PrintRefundPaymentReceiptMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector12PrintRequest")
@interface PrintRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// options for a request to read card data
SWIFT_CLASS("_TtC15CloverConnector19ReadCardDataRequest")
@interface ReadCardDataRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// response to a read card data request
SWIFT_CLASS("_TtC15CloverConnector20ReadCardDataResponse")
@interface ReadCardDataResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector25RefundPaymentPrintMessage")
@interface RefundPaymentPrintMessage : Message
@end


/// options for refunding a payment
SWIFT_CLASS("_TtC15CloverConnector20RefundPaymentRequest")
@interface RefundPaymentRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// response to a refund payment request
SWIFT_CLASS("_TtC15CloverConnector21RefundPaymentResponse")
@interface RefundPaymentResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector20RefundRequestMessage")
@interface RefundRequestMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector21RefundResponseMessage")
@interface RefundResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector38RegisterForCustomerProvidedDataMessage")
@interface RegisterForCustomerProvidedDataMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector38RegisterForCustomerProvidedDataRequest")
@interface RegisterForCustomerProvidedDataRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// response to a resetDevice request. It contains the state
/// of the device
SWIFT_CLASS("_TtC15CloverConnector19ResetDeviceResponse")
@interface ResetDeviceResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector26ResetDeviceResponseMessage")
@interface ResetDeviceResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector34RetrieveDeviceStatusRequestMessage")
@interface RetrieveDeviceStatusRequestMessage : Message
@end


/// response to a retrieve device status request
SWIFT_CLASS("_TtC15CloverConnector28RetrieveDeviceStatusResponse")
@interface RetrieveDeviceStatusResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector35RetrieveDeviceStatusResponseMessage")
@interface RetrieveDeviceStatusResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector29RetrievePaymentRequestMessage")
@interface RetrievePaymentRequestMessage : Message
@end


/// response to a retrieve payment request
SWIFT_CLASS("_TtC15CloverConnector23RetrievePaymentResponse")
@interface RetrievePaymentResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector30RetrievePaymentResponseMessage")
@interface RetrievePaymentResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector37RetrievePendingPaymentsRequestMessage")
@interface RetrievePendingPaymentsRequestMessage : Message
@end


/// resopnse to a retrieve pending payments request
SWIFT_CLASS("_TtC15CloverConnector31RetrievePendingPaymentsResponse")
@interface RetrievePendingPaymentsResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector23RetrievePrintersRequest")
@interface RetrievePrintersRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector30RetrievePrintersRequestMessage")
@interface RetrievePrintersRequestMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24RetrievePrintersResponse")
@interface RetrievePrintersResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector31RetrievePrintersResponseMessage")
@interface RetrievePrintersResponseMessage : Message
@end


/// Contains configuration options for processing a sale.
SWIFT_CLASS("_TtC15CloverConnector11SaleRequest")
@interface SaleRequest : TransactionRequest
@end


/// response to a sale request
SWIFT_CLASS("_TtC15CloverConnector12SaleResponse")
@interface SaleResponse : PaymentResponse
@end


SWIFT_CLASS("_TtC15CloverConnector32ShowPaymentReceiptOptionsMessage")
@interface ShowPaymentReceiptOptionsMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector25ShowReceiptOptionsMessage")
@interface ShowReceiptOptionsMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector33ShowReceiptOptionsResponseMessage")
@interface ShowReceiptOptionsResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector25ShowThankYouScreenMessage")
@interface ShowThankYouScreenMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24ShowWelcomeScreenMessage")
@interface ShowWelcomeScreenMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24SignatureVerifiedMessage")
@interface SignatureVerifiedMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector15TerminalMessage")
@interface TerminalMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector16TextPrintMessage")
@interface TextPrintMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector15TipAddedMessage")
@interface TipAddedMessage : Message
@end


/// options for a tip adjust request
SWIFT_CLASS("_TtC15CloverConnector20TipAdjustAuthRequest")
@interface TipAdjustAuthRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// response to a tip adjust request
SWIFT_CLASS("_TtC15CloverConnector21TipAdjustAuthResponse")
@interface TipAdjustAuthResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector16TipAdjustMessage")
@interface TipAdjustMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24TipAdjustResponseMessage")
@interface TipAdjustResponseMessage : Message
@end



SWIFT_CLASS("_TtC15CloverConnector21TxStartRequestMessage")
@interface TxStartRequestMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector22TxStartResponseMessage")
@interface TxStartResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector14TxStateMessage")
@interface TxStateMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector14UiStateMessage")
@interface UiStateMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector16VaultCardMessage")
@interface VaultCardMessage : Message
@end


/// options for a vault card request
SWIFT_CLASS("_TtC15CloverConnector16VaultCardRequest")
@interface VaultCardRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// resonse to a vault card request
SWIFT_CLASS("_TtC15CloverConnector17VaultCardResponse")
@interface VaultCardResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector24VaultCardResponseMessage")
@interface VaultCardResponseMessage : Message
@end


/// request information for a request initiated by the device
/// for a transaction
SWIFT_CLASS("_TtC15CloverConnector22VerifySignatureRequest")
@interface VerifySignatureRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector18VoidPaymentMessage")
@interface VoidPaymentMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24VoidPaymentRefundRequest")
@interface VoidPaymentRefundRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector25VoidPaymentRefundResponse")
@interface VoidPaymentRefundResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// options for void payment request
SWIFT_CLASS("_TtC15CloverConnector18VoidPaymentRequest")
@interface VoidPaymentRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// response to a void payment request
SWIFT_CLASS("_TtC15CloverConnector19VoidPaymentResponse")
@interface VoidPaymentResponse : PaymentResponse
@end


SWIFT_CLASS("_TtC15CloverConnector26VoidPaymentResponseMessage")
@interface VoidPaymentResponseMessage : Message
@end



SWIFT_CLASS("_TtC15CloverConnector28WebSocketDeviceConfiguration")
@interface WebSocketDeviceConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#elif defined(__x86_64__) && __x86_64__
// Generated by Apple Swift version 5.9.2 (swiftlang-5.9.2.2.56 clang-1500.1.0.2.5)
#ifndef CLOVERCONNECTOR_SWIFT_H
#define CLOVERCONNECTOR_SWIFT_H
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wgcc-compat"

#if !defined(__has_include)
# define __has_include(x) 0
#endif
#if !defined(__has_attribute)
# define __has_attribute(x) 0
#endif
#if !defined(__has_feature)
# define __has_feature(x) 0
#endif
#if !defined(__has_warning)
# define __has_warning(x) 0
#endif

#if __has_include(<swift/objc-prologue.h>)
# include <swift/objc-prologue.h>
#endif

#pragma clang diagnostic ignored "-Wauto-import"
#if defined(__OBJC__)
#include <Foundation/Foundation.h>
#endif
#if defined(__cplusplus)
#include <cstdint>
#include <cstddef>
#include <cstdbool>
#include <cstring>
#include <stdlib.h>
#include <new>
#include <type_traits>
#else
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <string.h>
#endif
#if defined(__cplusplus)
#if defined(__arm64e__) && __has_include(<ptrauth.h>)
# include <ptrauth.h>
#else
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wreserved-macro-identifier"
# ifndef __ptrauth_swift_value_witness_function_pointer
#  define __ptrauth_swift_value_witness_function_pointer(x)
# endif
# ifndef __ptrauth_swift_class_method_pointer
#  define __ptrauth_swift_class_method_pointer(x)
# endif
#pragma clang diagnostic pop
#endif
#endif

#if !defined(SWIFT_TYPEDEFS)
# define SWIFT_TYPEDEFS 1
# if __has_include(<uchar.h>)
#  include <uchar.h>
# elif !defined(__cplusplus)
typedef uint_least16_t char16_t;
typedef uint_least32_t char32_t;
# endif
typedef float swift_float2  __attribute__((__ext_vector_type__(2)));
typedef float swift_float3  __attribute__((__ext_vector_type__(3)));
typedef float swift_float4  __attribute__((__ext_vector_type__(4)));
typedef double swift_double2  __attribute__((__ext_vector_type__(2)));
typedef double swift_double3  __attribute__((__ext_vector_type__(3)));
typedef double swift_double4  __attribute__((__ext_vector_type__(4)));
typedef int swift_int2  __attribute__((__ext_vector_type__(2)));
typedef int swift_int3  __attribute__((__ext_vector_type__(3)));
typedef int swift_int4  __attribute__((__ext_vector_type__(4)));
typedef unsigned int swift_uint2  __attribute__((__ext_vector_type__(2)));
typedef unsigned int swift_uint3  __attribute__((__ext_vector_type__(3)));
typedef unsigned int swift_uint4  __attribute__((__ext_vector_type__(4)));
#endif

#if !defined(SWIFT_PASTE)
# define SWIFT_PASTE_HELPER(x, y) x##y
# define SWIFT_PASTE(x, y) SWIFT_PASTE_HELPER(x, y)
#endif
#if !defined(SWIFT_METATYPE)
# define SWIFT_METATYPE(X) Class
#endif
#if !defined(SWIFT_CLASS_PROPERTY)
# if __has_feature(objc_class_property)
#  define SWIFT_CLASS_PROPERTY(...) __VA_ARGS__
# else
#  define SWIFT_CLASS_PROPERTY(...) 
# endif
#endif
#if !defined(SWIFT_RUNTIME_NAME)
# if __has_attribute(objc_runtime_name)
#  define SWIFT_RUNTIME_NAME(X) __attribute__((objc_runtime_name(X)))
# else
#  define SWIFT_RUNTIME_NAME(X) 
# endif
#endif
#if !defined(SWIFT_COMPILE_NAME)
# if __has_attribute(swift_name)
#  define SWIFT_COMPILE_NAME(X) __attribute__((swift_name(X)))
# else
#  define SWIFT_COMPILE_NAME(X) 
# endif
#endif
#if !defined(SWIFT_METHOD_FAMILY)
# if __has_attribute(objc_method_family)
#  define SWIFT_METHOD_FAMILY(X) __attribute__((objc_method_family(X)))
# else
#  define SWIFT_METHOD_FAMILY(X) 
# endif
#endif
#if !defined(SWIFT_NOESCAPE)
# if __has_attribute(noescape)
#  define SWIFT_NOESCAPE __attribute__((noescape))
# else
#  define SWIFT_NOESCAPE 
# endif
#endif
#if !defined(SWIFT_RELEASES_ARGUMENT)
# if __has_attribute(ns_consumed)
#  define SWIFT_RELEASES_ARGUMENT __attribute__((ns_consumed))
# else
#  define SWIFT_RELEASES_ARGUMENT 
# endif
#endif
#if !defined(SWIFT_WARN_UNUSED_RESULT)
# if __has_attribute(warn_unused_result)
#  define SWIFT_WARN_UNUSED_RESULT __attribute__((warn_unused_result))
# else
#  define SWIFT_WARN_UNUSED_RESULT 
# endif
#endif
#if !defined(SWIFT_NORETURN)
# if __has_attribute(noreturn)
#  define SWIFT_NORETURN __attribute__((noreturn))
# else
#  define SWIFT_NORETURN 
# endif
#endif
#if !defined(SWIFT_CLASS_EXTRA)
# define SWIFT_CLASS_EXTRA 
#endif
#if !defined(SWIFT_PROTOCOL_EXTRA)
# define SWIFT_PROTOCOL_EXTRA 
#endif
#if !defined(SWIFT_ENUM_EXTRA)
# define SWIFT_ENUM_EXTRA 
#endif
#if !defined(SWIFT_CLASS)
# if __has_attribute(objc_subclassing_restricted)
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_subclassing_restricted)) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# else
#  define SWIFT_CLASS(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
#  define SWIFT_CLASS_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_CLASS_EXTRA
# endif
#endif
#if !defined(SWIFT_RESILIENT_CLASS)
# if __has_attribute(objc_class_stub)
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME) __attribute__((objc_class_stub))
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) __attribute__((objc_class_stub)) SWIFT_CLASS_NAMED(SWIFT_NAME)
# else
#  define SWIFT_RESILIENT_CLASS(SWIFT_NAME) SWIFT_CLASS(SWIFT_NAME)
#  define SWIFT_RESILIENT_CLASS_NAMED(SWIFT_NAME) SWIFT_CLASS_NAMED(SWIFT_NAME)
# endif
#endif
#if !defined(SWIFT_PROTOCOL)
# define SWIFT_PROTOCOL(SWIFT_NAME) SWIFT_RUNTIME_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
# define SWIFT_PROTOCOL_NAMED(SWIFT_NAME) SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_PROTOCOL_EXTRA
#endif
#if !defined(SWIFT_EXTENSION)
# define SWIFT_EXTENSION(M) SWIFT_PASTE(M##_Swift_, __LINE__)
#endif
#if !defined(OBJC_DESIGNATED_INITIALIZER)
# if __has_attribute(objc_designated_initializer)
#  define OBJC_DESIGNATED_INITIALIZER __attribute__((objc_designated_initializer))
# else
#  define OBJC_DESIGNATED_INITIALIZER 
# endif
#endif
#if !defined(SWIFT_ENUM_ATTR)
# if __has_attribute(enum_extensibility)
#  define SWIFT_ENUM_ATTR(_extensibility) __attribute__((enum_extensibility(_extensibility)))
# else
#  define SWIFT_ENUM_ATTR(_extensibility) 
# endif
#endif
#if !defined(SWIFT_ENUM)
# define SWIFT_ENUM(_type, _name, _extensibility) enum _name : _type _name; enum SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# if __has_feature(generalized_swift_name)
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) enum _name : _type _name SWIFT_COMPILE_NAME(SWIFT_NAME); enum SWIFT_COMPILE_NAME(SWIFT_NAME) SWIFT_ENUM_ATTR(_extensibility) SWIFT_ENUM_EXTRA _name : _type
# else
#  define SWIFT_ENUM_NAMED(_type, _name, SWIFT_NAME, _extensibility) SWIFT_ENUM(_type, _name, _extensibility)
# endif
#endif
#if !defined(SWIFT_UNAVAILABLE)
# define SWIFT_UNAVAILABLE __attribute__((unavailable))
#endif
#if !defined(SWIFT_UNAVAILABLE_MSG)
# define SWIFT_UNAVAILABLE_MSG(msg) __attribute__((unavailable(msg)))
#endif
#if !defined(SWIFT_AVAILABILITY)
# define SWIFT_AVAILABILITY(plat, ...) __attribute__((availability(plat, __VA_ARGS__)))
#endif
#if !defined(SWIFT_WEAK_IMPORT)
# define SWIFT_WEAK_IMPORT __attribute__((weak_import))
#endif
#if !defined(SWIFT_DEPRECATED)
# define SWIFT_DEPRECATED __attribute__((deprecated))
#endif
#if !defined(SWIFT_DEPRECATED_MSG)
# define SWIFT_DEPRECATED_MSG(...) __attribute__((deprecated(__VA_ARGS__)))
#endif
#if !defined(SWIFT_DEPRECATED_OBJC)
# if __has_feature(attribute_diagnose_if_objc)
#  define SWIFT_DEPRECATED_OBJC(Msg) __attribute__((diagnose_if(1, Msg, "warning")))
# else
#  define SWIFT_DEPRECATED_OBJC(Msg) SWIFT_DEPRECATED_MSG(Msg)
# endif
#endif
#if defined(__OBJC__)
#if !defined(IBSegueAction)
# define IBSegueAction 
#endif
#endif
#if !defined(SWIFT_EXTERN)
# if defined(__cplusplus)
#  define SWIFT_EXTERN extern "C"
# else
#  define SWIFT_EXTERN extern
# endif
#endif
#if !defined(SWIFT_CALL)
# define SWIFT_CALL __attribute__((swiftcall))
#endif
#if !defined(SWIFT_INDIRECT_RESULT)
# define SWIFT_INDIRECT_RESULT __attribute__((swift_indirect_result))
#endif
#if !defined(SWIFT_CONTEXT)
# define SWIFT_CONTEXT __attribute__((swift_context))
#endif
#if !defined(SWIFT_ERROR_RESULT)
# define SWIFT_ERROR_RESULT __attribute__((swift_error_result))
#endif
#if defined(__cplusplus)
# define SWIFT_NOEXCEPT noexcept
#else
# define SWIFT_NOEXCEPT 
#endif
#if !defined(SWIFT_C_INLINE_THUNK)
# if __has_attribute(always_inline)
# if __has_attribute(nodebug)
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline)) __attribute__((nodebug))
# else
#  define SWIFT_C_INLINE_THUNK inline __attribute__((always_inline))
# endif
# else
#  define SWIFT_C_INLINE_THUNK inline
# endif
#endif
#if defined(_WIN32)
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL __declspec(dllimport)
#endif
#else
#if !defined(SWIFT_IMPORT_STDLIB_SYMBOL)
# define SWIFT_IMPORT_STDLIB_SYMBOL 
#endif
#endif
#if defined(__OBJC__)
#if __has_feature(objc_modules)
#if __has_warning("-Watimport-in-framework-header")
#pragma clang diagnostic ignored "-Watimport-in-framework-header"
#endif
@import Foundation;
@import ObjectiveC;
#endif

#endif
#pragma clang diagnostic ignored "-Wproperty-attribute-mismatch"
#pragma clang diagnostic ignored "-Wduplicate-method-arg"
#if __has_warning("-Wpragma-clang-attribute")
# pragma clang diagnostic ignored "-Wpragma-clang-attribute"
#endif
#pragma clang diagnostic ignored "-Wunknown-pragmas"
#pragma clang diagnostic ignored "-Wnullability"
#pragma clang diagnostic ignored "-Wdollar-in-identifier-extension"

#if __has_attribute(external_source_symbol)
# pragma push_macro("any")
# undef any
# pragma clang attribute push(__attribute__((external_source_symbol(language="Swift", defined_in="CloverConnector",generated_declaration))), apply_to=any(function,enum,objc_interface,objc_category,objc_protocol))
# pragma pop_macro("any")
#endif

#if defined(__OBJC__)

SWIFT_CLASS("_TtC15CloverConnector7Message")
@interface Message : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector22AcknowledgementMessage")
@interface AcknowledgementMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector25BaseActivityRemoteMessage")
@interface BaseActivityRemoteMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector27ActivityMessageFromActivity")
@interface ActivityMessageFromActivity : BaseActivityRemoteMessage
@end


SWIFT_CLASS("_TtC15CloverConnector25ActivityMessageToActivity")
@interface ActivityMessageToActivity : BaseActivityRemoteMessage
@end


SWIFT_CLASS("_TtC15CloverConnector15ActivityRequest")
@interface ActivityRequest : Message
@end


SWIFT_CLASS("_TtC15CloverConnector23ActivityResponseMessage")
@interface ActivityResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector22BaseTransactionRequest")
@interface BaseTransactionRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Provides base capabilities for TransactionRequests like SaleRequest, AuthRequest, etc.
SWIFT_CLASS("_TtC15CloverConnector18TransactionRequest")
@interface TransactionRequest : BaseTransactionRequest
@end


/// The request sent to the Auth method. ‘amount’ is the only field required.
SWIFT_CLASS("_TtC15CloverConnector11AuthRequest")
@interface AuthRequest : TransactionRequest
@end


/// A base response for
SWIFT_CLASS("_TtC15CloverConnector12BaseResponse")
@interface BaseResponse : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector15PaymentResponse")
@interface PaymentResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The response to an auth request
SWIFT_CLASS("_TtC15CloverConnector12AuthResponse")
@interface AuthResponse : PaymentResponse
@end


/// Base message used for exchanging messages between the POS and a Custom Activity
SWIFT_CLASS("_TtC15CloverConnector19BaseActivityMessage")
@interface BaseActivityMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end





SWIFT_CLASS("_TtC15CloverConnector12BreakMessage")
@interface BreakMessage : Message
@end


/// options for capturing a pre-auth
SWIFT_CLASS("_TtC15CloverConnector21CapturePreAuthRequest")
@interface CapturePreAuthRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector30CapturePreAuthRequestMessageV1")
@interface CapturePreAuthRequestMessageV1 : Message
@end


/// response to a capturePreAuth request
SWIFT_CLASS("_TtC15CloverConnector22CapturePreAuthResponse")
@interface CapturePreAuthResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector29CapturePreAuthResponseMessage")
@interface CapturePreAuthResponseMessage : Message
@end

@class NSCoder;

SWIFT_CLASS("_TtC15CloverConnector8CardData")
@interface CardData : NSObject <NSCoding>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector22CardDataRequestMessage")
@interface CardDataRequestMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector23CardDataResponseMessage")
@interface CardDataResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector23CashbackSelectedMessage")
@interface CashbackSelectedMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector15CloseoutRequest")
@interface CloseoutRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector22CloseoutRequestMessage")
@interface CloseoutRequestMessage : Message
@end


/// response to a closeout request
SWIFT_CLASS("_TtC15CloverConnector16CloseoutResponse")
@interface CloseoutResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector23CloseoutResponseMessage")
@interface CloseoutResponseMessage : Message
@end


/// generic message for unanticipated or unexpected errors
SWIFT_CLASS("_TtC15CloverConnector22CloverDeviceErrorEvent")
@interface CloverDeviceErrorEvent : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector17CloverDeviceEvent")
@interface CloverDeviceEvent : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// requests the device log a message to the server
SWIFT_CLASS("_TtC15CloverConnector22CloverDeviceLogMessage")
@interface CloverDeviceLogMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector15CloverTransport")
@interface CloverTransport : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector21ConfirmPaymentMessage")
@interface ConfirmPaymentMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector21ConfirmPaymentRequest")
@interface ConfirmPaymentRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector18CreditPrintMessage")
@interface CreditPrintMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector21CustomActivityRequest")
@interface CustomActivityRequest : BaseActivityMessage
@end


/// response when a custom activity is finished
SWIFT_CLASS("_TtC15CloverConnector22CustomActivityResponse")
@interface CustomActivityResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector19CustomerInfoMessage")
@interface CustomerInfoMessage : Message
@end


/// Loyalty API
/// Transfers the data provided by the customer to the semi-integrated POS
SWIFT_CLASS("_TtC15CloverConnector25CustomerProvidedDataEvent")
@interface CustomerProvidedDataEvent : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector27CustomerProvidedDataMessage")
@interface CustomerProvidedDataMessage : Message
@end



SWIFT_CLASS("_TtC15CloverConnector25DeclineCreditPrintMessage")
@interface DeclineCreditPrintMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector26DeclinePaymentPrintMessage")
@interface DeclinePaymentPrintMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector30DefaultCloverConnectorListener")
@interface DefaultCloverConnectorListener : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Contains information about the connected device
SWIFT_CLASS("_TtC15CloverConnector10DeviceInfo")
@interface DeviceInfo : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector23DiscoveryRequestMessage")
@interface DiscoveryRequestMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24DiscoveryResponseMessage")
@interface DiscoveryResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector12DisplayOrder")
@interface DisplayOrder : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector28DisplayReceiptOptionsRequest")
@interface DisplayReceiptOptionsRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector29DisplayReceiptOptionsResponse")
@interface DisplayReceiptOptionsResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector19FinishCancelMessage")
@interface FinishCancelMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector15FinishOkMessage")
@interface FinishOkMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector17ImagePrintMessage")
@interface ImagePrintMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector23IncrementPreauthMessage")
@interface IncrementPreauthMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24IncrementPreauthResponse")
@interface IncrementPreauthResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// The response
SWIFT_CLASS("_TtC15CloverConnector31IncrementPreauthResponseMessage")
@interface IncrementPreauthResponseMessage : Message
@end

@class NSString;

SWIFT_CLASS("_TtC15CloverConnector11InputOption")
@interface InputOption : NSObject
@property (nonatomic, copy) NSString * _Nonnull description;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector30InvalidStateTransitionResponse")
@interface InvalidStateTransitionResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector15KeyPressMessage")
@interface KeyPressMessage : Message
@end


/// options for a manual refund
SWIFT_CLASS("_TtC15CloverConnector19ManualRefundRequest")
@interface ManualRefundRequest : TransactionRequest
@end


/// response to a manual refund
SWIFT_CLASS("_TtC15CloverConnector20ManualRefundResponse")
@interface ManualRefundResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Contains merchant information as well as some high level capabilities
SWIFT_CLASS("_TtC15CloverConnector12MerchantInfo")
@interface MerchantInfo : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end



/// Contains the message information send from a custom Activity
SWIFT_CLASS("_TtC15CloverConnector19MessageFromActivity")
@interface MessageFromActivity : BaseActivityMessage
@end


/// Contains the message information sent to a custom Activity
SWIFT_CLASS("_TtC15CloverConnector17MessageToActivity")
@interface MessageToActivity : BaseActivityMessage
@end


SWIFT_CLASS("_TtC15CloverConnector21OpenCashDrawerMessage")
@interface OpenCashDrawerMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector21OpenCashDrawerRequest")
@interface OpenCashDrawerRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector29OrderActionAddDiscountMessage")
@interface OrderActionAddDiscountMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector26OrderActionLineItemMessage")
@interface OrderActionLineItemMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector32OrderActionRemoveDiscountMessage")
@interface OrderActionRemoveDiscountMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector32OrderActionRemoveLineItemMessage")
@interface OrderActionRemoveLineItemMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector26OrderActionResponseMessage")
@interface OrderActionResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector18OrderUpdateMessage")
@interface OrderUpdateMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector18PartialAuthMessage")
@interface PartialAuthMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector23PaymentConfirmedMessage")
@interface PaymentConfirmedMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector31PaymentPrintMerchantCopyMessage")
@interface PaymentPrintMerchantCopyMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector19PaymentPrintMessage")
@interface PaymentPrintMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector22PaymentRejectedMessage")
@interface PaymentRejectedMessage : Message
@end



SWIFT_CLASS("_TtC15CloverConnector20PaymentVoidedMessage")
@interface PaymentVoidedMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector19PendingPaymentEntry")
@interface PendingPaymentEntry : NSObject <NSCoding>
- (void)encodeWithCoder:(NSCoder * _Nonnull)aCoder;
- (nonnull instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// options for a pre-authorization request
SWIFT_CLASS("_TtC15CloverConnector14PreAuthRequest")
@interface PreAuthRequest : BaseTransactionRequest
@end


/// response to a pre-auth request
SWIFT_CLASS("_TtC15CloverConnector15PreAuthResponse")
@interface PreAuthResponse : PaymentResponse
@end


SWIFT_CLASS("_TtC15CloverConnector21PrintJobStatusRequest")
@interface PrintJobStatusRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector28PrintJobStatusRequestMessage")
@interface PrintJobStatusRequestMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector22PrintJobStatusResponse")
@interface PrintJobStatusResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector29PrintJobStatusResponseMessage")
@interface PrintJobStatusResponseMessage : Message
@end


/// Callback to the POS to request a manual refund declined receipt
SWIFT_CLASS("_TtC15CloverConnector38PrintManualRefundDeclineReceiptMessage")
@interface PrintManualRefundDeclineReceiptMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Callback to request the POS print a refund for a
/// ManualRefund
SWIFT_CLASS("_TtC15CloverConnector31PrintManualRefundReceiptMessage")
@interface PrintManualRefundReceiptMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Callback to the POS to request a payment declined receipt
SWIFT_CLASS("_TtC15CloverConnector33PrintPaymentDeclineReceiptMessage")
@interface PrintPaymentDeclineReceiptMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// <ul>
///   <li>
///     Callback to the POS to request a merchant copy of the payment receipt
///   </li>
/// </ul>
SWIFT_CLASS("_TtC15CloverConnector38PrintPaymentMerchantCopyReceiptMessage")
@interface PrintPaymentMerchantCopyReceiptMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// Callback to the POS to request a payment receipt be printed
SWIFT_CLASS("_TtC15CloverConnector26PrintPaymentReceiptMessage")
@interface PrintPaymentReceiptMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// <ul>
///   <li>
///     Callback to the POS to request a refund payment receipt
///   </li>
/// </ul>
SWIFT_CLASS("_TtC15CloverConnector32PrintRefundPaymentReceiptMessage")
@interface PrintRefundPaymentReceiptMessage : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector12PrintRequest")
@interface PrintRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// options for a request to read card data
SWIFT_CLASS("_TtC15CloverConnector19ReadCardDataRequest")
@interface ReadCardDataRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// response to a read card data request
SWIFT_CLASS("_TtC15CloverConnector20ReadCardDataResponse")
@interface ReadCardDataResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector25RefundPaymentPrintMessage")
@interface RefundPaymentPrintMessage : Message
@end


/// options for refunding a payment
SWIFT_CLASS("_TtC15CloverConnector20RefundPaymentRequest")
@interface RefundPaymentRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// response to a refund payment request
SWIFT_CLASS("_TtC15CloverConnector21RefundPaymentResponse")
@interface RefundPaymentResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector20RefundRequestMessage")
@interface RefundRequestMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector21RefundResponseMessage")
@interface RefundResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector38RegisterForCustomerProvidedDataMessage")
@interface RegisterForCustomerProvidedDataMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector38RegisterForCustomerProvidedDataRequest")
@interface RegisterForCustomerProvidedDataRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// response to a resetDevice request. It contains the state
/// of the device
SWIFT_CLASS("_TtC15CloverConnector19ResetDeviceResponse")
@interface ResetDeviceResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector26ResetDeviceResponseMessage")
@interface ResetDeviceResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector34RetrieveDeviceStatusRequestMessage")
@interface RetrieveDeviceStatusRequestMessage : Message
@end


/// response to a retrieve device status request
SWIFT_CLASS("_TtC15CloverConnector28RetrieveDeviceStatusResponse")
@interface RetrieveDeviceStatusResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector35RetrieveDeviceStatusResponseMessage")
@interface RetrieveDeviceStatusResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector29RetrievePaymentRequestMessage")
@interface RetrievePaymentRequestMessage : Message
@end


/// response to a retrieve payment request
SWIFT_CLASS("_TtC15CloverConnector23RetrievePaymentResponse")
@interface RetrievePaymentResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector30RetrievePaymentResponseMessage")
@interface RetrievePaymentResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector37RetrievePendingPaymentsRequestMessage")
@interface RetrievePendingPaymentsRequestMessage : Message
@end


/// resopnse to a retrieve pending payments request
SWIFT_CLASS("_TtC15CloverConnector31RetrievePendingPaymentsResponse")
@interface RetrievePendingPaymentsResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector23RetrievePrintersRequest")
@interface RetrievePrintersRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector30RetrievePrintersRequestMessage")
@interface RetrievePrintersRequestMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24RetrievePrintersResponse")
@interface RetrievePrintersResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector31RetrievePrintersResponseMessage")
@interface RetrievePrintersResponseMessage : Message
@end


/// Contains configuration options for processing a sale.
SWIFT_CLASS("_TtC15CloverConnector11SaleRequest")
@interface SaleRequest : TransactionRequest
@end


/// response to a sale request
SWIFT_CLASS("_TtC15CloverConnector12SaleResponse")
@interface SaleResponse : PaymentResponse
@end


SWIFT_CLASS("_TtC15CloverConnector32ShowPaymentReceiptOptionsMessage")
@interface ShowPaymentReceiptOptionsMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector25ShowReceiptOptionsMessage")
@interface ShowReceiptOptionsMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector33ShowReceiptOptionsResponseMessage")
@interface ShowReceiptOptionsResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector25ShowThankYouScreenMessage")
@interface ShowThankYouScreenMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24ShowWelcomeScreenMessage")
@interface ShowWelcomeScreenMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24SignatureVerifiedMessage")
@interface SignatureVerifiedMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector15TerminalMessage")
@interface TerminalMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector16TextPrintMessage")
@interface TextPrintMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector15TipAddedMessage")
@interface TipAddedMessage : Message
@end


/// options for a tip adjust request
SWIFT_CLASS("_TtC15CloverConnector20TipAdjustAuthRequest")
@interface TipAdjustAuthRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// response to a tip adjust request
SWIFT_CLASS("_TtC15CloverConnector21TipAdjustAuthResponse")
@interface TipAdjustAuthResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector16TipAdjustMessage")
@interface TipAdjustMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24TipAdjustResponseMessage")
@interface TipAdjustResponseMessage : Message
@end



SWIFT_CLASS("_TtC15CloverConnector21TxStartRequestMessage")
@interface TxStartRequestMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector22TxStartResponseMessage")
@interface TxStartResponseMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector14TxStateMessage")
@interface TxStateMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector14UiStateMessage")
@interface UiStateMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector16VaultCardMessage")
@interface VaultCardMessage : Message
@end


/// options for a vault card request
SWIFT_CLASS("_TtC15CloverConnector16VaultCardRequest")
@interface VaultCardRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


/// resonse to a vault card request
SWIFT_CLASS("_TtC15CloverConnector17VaultCardResponse")
@interface VaultCardResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector24VaultCardResponseMessage")
@interface VaultCardResponseMessage : Message
@end


/// request information for a request initiated by the device
/// for a transaction
SWIFT_CLASS("_TtC15CloverConnector22VerifySignatureRequest")
@interface VerifySignatureRequest : NSObject
- (nonnull instancetype)init OBJC_DESIGNATED_INITIALIZER;
@end


SWIFT_CLASS("_TtC15CloverConnector18VoidPaymentMessage")
@interface VoidPaymentMessage : Message
@end


SWIFT_CLASS("_TtC15CloverConnector24VoidPaymentRefundRequest")
@interface VoidPaymentRefundRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


SWIFT_CLASS("_TtC15CloverConnector25VoidPaymentRefundResponse")
@interface VoidPaymentRefundResponse : BaseResponse
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// options for void payment request
SWIFT_CLASS("_TtC15CloverConnector18VoidPaymentRequest")
@interface VoidPaymentRequest : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end


/// response to a void payment request
SWIFT_CLASS("_TtC15CloverConnector19VoidPaymentResponse")
@interface VoidPaymentResponse : PaymentResponse
@end


SWIFT_CLASS("_TtC15CloverConnector26VoidPaymentResponseMessage")
@interface VoidPaymentResponseMessage : Message
@end



SWIFT_CLASS("_TtC15CloverConnector28WebSocketDeviceConfiguration")
@interface WebSocketDeviceConfiguration : NSObject
- (nonnull instancetype)init SWIFT_UNAVAILABLE;
+ (nonnull instancetype)new SWIFT_UNAVAILABLE_MSG("-init is unavailable");
@end

#endif
#if __has_attribute(external_source_symbol)
# pragma clang attribute pop
#endif
#if defined(__cplusplus)
#endif
#pragma clang diagnostic pop
#endif

#else
#error unsupported Swift architecture
#endif
